# .travis.yml
osx_image: xcode7.3
language: generic
matrix:
    include:
        - os: osx
          env: TYPE=xcode7
        # - os: osx
        #   env: TYPE=smp
# install: if [[ "$TYPE" == "spm" ]]; then eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"; fi
script: ./test $TYPE
notifications:
    email: 
        on_success: false