#!/bin/bash
# ./test script

set -e # exit on failure

function xcode_tests
{
    (
        set -e
        set -x # print commands executed; use subshell to avoid having to print 'set +x' to disable it
        
        xcodebuild -project SwiftOpenCL.xcodeproj -scheme SwiftOpenCL -destination "platform=OS X"
    )
    echo
    echo "Xcode build passed"
}

function spm_tests
{
    (
        set -e
        set -x # print commands executed; use subshell to avoid having to print 'set +x' to disable it
        
        swift build --clean
        swift build
        # swift test
    )
    echo
    echo "SPM build passed"
}
    
for arg in "$@"
do
    case $arg in 
        "spm") spm_tests;;
        "xcode") xcode_tests;;
    esac
done