import OpenCL

//enum ClError: cl_int, ErrorType {
//	// run-time and JIT compiler errors
//	case CL_SUCCESS = 0
//	case CL_DEVICE_NOT_FOUND = -1
//	case CL_DEVICE_NOT_AVAILABLE = -2
//	case CL_COMPILER_NOT_AVAILABLE = -3
//	case CL_MEM_OBJECT_ALLOCATION_FAILURE = -4
//	case CL_OUT_OF_RESOURCES = -5
//	case CL_OUT_OF_HOST_MEMORY = -6
//	case CL_PROFILING_INFO_NOT_AVAILABLE = -7
//	case CL_MEM_COPY_OVERLAP = -8
//	case CL_IMAGE_FORMAT_MISMATCH = -9
//	case CL_IMAGE_FORMAT_NOT_SUPPORTED = -10
//	case CL_BUILD_PROGRAM_FAILURE = -11
//	case CL_MAP_FAILURE = -12
//	case CL_MISALIGNED_SUB_BUFFER_OFFSET = -13
//	case CL_EXEC_STATUS_ERROR_FOR_EVENTS_IN_WAIT_LIST = -14
//	case CL_COMPILE_PROGRAM_FAILURE = -15
//	case CL_LINKER_NOT_AVAILABLE = -16
//	case CL_LINK_PROGRAM_FAILURE = -17
//	case CL_DEVICE_PARTITION_FAILED = -18
//	case CL_KERNEL_ARG_INFO_NOT_AVAILABLE = -19
//
//	// compile-time errors
//	case CL_INVALID_VALUE = -30
//	case CL_INVALID_DEVICE_TYPE = -31
//	case CL_INVALID_PLATFORM = -32
//	case CL_INVALID_DEVICE = -33
//	case CL_INVALID_CONTEXT = -34
//	case CL_INVALID_QUEUE_PROPERTIES = -35
//	case CL_INVALID_COMMAND_QUEUE = -36
//	case CL_INVALID_HOST_PTR = -37
//	case CL_INVALID_MEM_OBJECT = -38
//	case CL_INVALID_IMAGE_FORMAT_DESCRIPTOR = -39
//	case CL_INVALID_IMAGE_SIZE = -40
//	case CL_INVALID_SAMPLER = -41
//	case CL_INVALID_BINARY = -42
//	case CL_INVALID_BUILD_OPTIONS = -43
//	case CL_INVALID_PROGRAM = -44
//	case CL_INVALID_PROGRAM_EXECUTABLE = -45
//	case CL_INVALID_KERNEL_NAME = -46
//	case CL_INVALID_KERNEL_DEFINITION = -47
//	case CL_INVALID_KERNEL = -48
//	case CL_INVALID_ARG_INDEX = -49
//	case CL_INVALID_ARG_VALUE = -50
//	case CL_INVALID_ARG_SIZE = -51
//	case CL_INVALID_KERNEL_ARGS = -52
//	case CL_INVALID_WORK_DIMENSION = -53
//	case CL_INVALID_WORK_GROUP_SIZE = -54
//	case CL_INVALID_WORK_ITEM_SIZE = -55
//	case CL_INVALID_GLOBAL_OFFSET = -56
//	case CL_INVALID_EVENT_WAIT_LIST = -57
//	case CL_INVALID_EVENT = -58
//	case CL_INVALID_OPERATION = -59
//	case CL_INVALID_GL_OBJECT = -60
//	case CL_INVALID_BUFFER_SIZE = -61
//	case CL_INVALID_MIP_LEVEL = -62
//	case CL_INVALID_GLOBAL_WORK_SIZE = -63
//	case CL_INVALID_PROPERTY = -64
//	case CL_INVALID_IMAGE_DESCRIPTOR = -65
//	case CL_INVALID_COMPILER_OPTIONS = -66
//	case CL_INVALID_LINKER_OPTIONS = -67
//	case CL_INVALID_DEVICE_PARTITION_COUNT = -68
//
//	// extension errors
//	case CL_INVALID_GL_SHAREGROUP_REFERENCE_KHR = -1000
//	case CL_PLATFORM_NOT_FOUND_KHR = -1001
//	case CL_INVALID_D3D10_DEVICE_KHR = -1002
//	case CL_INVALID_D3D10_RESOURCE_KHR = -1003
//	case CL_D3D10_RESOURCE_ALREADY_ACQUIRED_KHR = -1004
//	case CL_D3D10_RESOURCE_NOT_ACQUIRED_KHR = -1005
//	case CL_UNKNOWN_ERROR = -999999
//}
